name: CDK PR Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validate CDK synth and diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::342811584933:role/SubstackGithubDeployRole
          role-session-name: ghactions
          aws-region: us-east-1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install CDK cli
        run: npm install -g aws-cdk

      - name: Run cdk synth
        run: cdk synth

      - name: Run cdk diff
        run: cdk diff
