name: Deploy Substack Infra

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install root dependencies
        run: npm ci

      - name: Install lambda dependencies
        working-directory: lambda
        run: npm ci

      - name: Build assets
        run: npm run build:all

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::342811584933:role/SubstackGithubDeployRole
          role-session-name: ghactions
          aws-region: us-east-1

      - name: Install CDK cli
        run: npm install -g aws-cdk

      - name: CDK deploy
        run: cdk deploy KaraSubstackFeedApiStack SubstackEmailSyncCIRole --require-approval never
